{{ if .Values.dnsSolvers }}
kind: ClusterIssuer
apiVersion: cert-manager.io/v1alpha2
metadata:
  name: {{ template "issuer.fullname" . }}-production
  labels:
    app.kubernetes.io/name: {{ include "issuer.name" . }}
    helm.sh/chart: {{ include "issuer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}spec:
acme:
  server: https://acme-v02.api.letsencrypt.org/directory
  email: {{ required "The 'email' value must be set!" .Values.email }}
  privateKeySecretRef:
    name: {{ .values.privateKeySecret.production }}
  solvers:
    - dns01: {{ .Values.dnsSolvers | toJson }}
{{ end }}